cache:
  key: "$CI_BUILD_REF_NAME debian:jessie"
  paths:
  - node_modules/

stages:
  - build
  - release
  - deploy

build:
  stage: build
  image: debian:jessie
  variables:
    NODE_ENV: "development"
  script:
    - apk add --update bash
    - apk add --update git && rm -rf /tmp/* /var/cache/apk/*

release:
  stage: release
  image: docker:latest
  only:
    - "master"
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: "overlay"
  before_script:
    - docker version
    - "docker info"
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - "docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest --pull ."
    - "docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest"
  after_script:
    - "docker logout ${CI_REGISTRY}"

deploy:
  stage: deploy
  image: gitlab/dind:latest
  only:
    - "master"
  services:
    - docker:dind
  before_script:
    - apt-get update -y && apt-get install sshpass
  script:
    - printf "/docker-script/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/${CI_COMMIT_SHA}"
    - sshpass -p "${DEPLOYMENT_SERVER_PASS}" ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no $DEPLOYMENT_SERVER_USER@$DEPLOYMENT_SERVER_IP "mkdir -p /home/development/docker-script/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}"
    - sshpass -p "${DEPLOYMENT_SERVER_PASS}" scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no ./docker-compose.yml ${DEPLOYMENT_SERVER_USER}@${DEPLOYMENT_SERVER_IP}:/home/development/docker-script/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/
    - sshpass -p "${DEPLOYMENT_SERVER_PASS}" ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no $DEPLOYMENT_SERVER_USER@$DEPLOYMENT_SERVER_IP "echo ${DEPLOYMENT_SERVER_PASS} | sudo -S ls && docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}; sudo docker-compose -f /home/development/docker-script/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/docker-compose.yml stop; sudo docker-compose -f /home/development/docker-script/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/docker-compose.yml rm ckan-jawa-barat --force; sudo docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest; sudo docker-compose -f /home/development/docker-script/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/docker-compose.yml up -d"